#:schema file:///home/trash/Desktop/repos/nazm/schema/config.schema.json

[server]
port = 8080
host = "0.0.0.0"
verbose = false
cors_origins = ["http://localhost:5173", "http://127.0.0.1:5173"]

[aria2]
host = "ws://127.0.0.1"
port = "6800"
secret = "foobar"
dir = "/home/trash/Downloads/aria2"

[tls]
cert = ""
key = ""

[app]
data_dir = "./nazm"
