#@aria2 tellStatus
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.tellStatus",
  "params": ["token:foobar", "26afd5dc52d097c8"]
}


###
#@aria2 getglobalstat
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getGlobalStat",
  "params": ["token:foobar"]
}

###
#@aria2 getFiles
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getFiles",
  "params": ["token:foobar", "84c61c6fd7906ba8"]
}

###
#@aria2 getFiles
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.unpause",
  "params": ["token:foobar", "ea54f44e2579d9de"]
}


###
#@aria2 pause
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.pause",
  "params": ["token:foobar", "7bf066f41831e19c"]
}

###
#@aria2 getPeers
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getPeers",
  "params": ["token:foobar", "894a5c770704bc79"]
}

###
#@aria2 getServers
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getServers",
  "params": ["token:foobar", "c7295eea905cabde"]
}

###
#@aria2 getUris
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getUris",
  "params": ["token:foobar", "1341cb2c6125ff1d"]
}

###

#@aria2 tellWaiting
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.tellWaiting",
  "params": ["token:foobar", 0, 10000]
}

###
#@aria2 tellActive
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.tellActive",
  "params": ["token:foobar"]
}

###
#@aria2 tellActive
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.forceRemove",
  "params": ["token:foobar", "695e1011ec96cb8b"]
}

###
#@aria2 getGlobalOption
POST http://localhost:6800/jsonrpc
Content-Type:application/json

{
  "jsonrpc":"2.0",
  "id":"nazm",
  "method":"aria2.getGlobalOption",
  "params": ["token:foobar"]
}

###
#@aria2 changeGlobalOption
POST http://localhost:6800/jsonrpc
Content-Type: application/json"

{
  "jsonrpc": "2.0",
  "id":"nazm",
  "method": "aria2.changeGlobalOption",
  "params": [
    "token:foobar", {
			"rpc-max-request-size": "1M"
  }]
}


###
#@aria2 addUri
POST http://localhost:6800/jsonrpc
Content-Type: application/json"

{
	"jsonrpc": "2.0",
		"id": "nazm",
		"method": "system.multicall",
		"params": [[
		{
			"methodName": "aria2.addUri",
			"params": [
				"token:foobar",
				["file:///home/trash/Downloads/A%20Moment%20of%20Romance%20II%20(1993)%201080p%20WEBRip%20x264%20-YTS.torrent"]
			]
		},
		{
			"methodName": "aria2.addUri",
			"params": [
				"token:foobar",
				["file:///home/trash/Downloads/A%20Moment%20of%20Romance%20II%20(1993)%201080p%20WEBRip%20x264%20-YTS.torrent"]
			]
		}
		]]
}'


###
WS ws://localhost:6800/jsonrpc




###

# @nazm login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "trasharia",
  "password": "checkcheck"
}

###
# @nazm get_history
# @attach-cookie-jar
GET http://localhost:8080/api/aria2/user/history


###
# @nazm remove
# @attach-cookie-jar
DELETE http://localhost:8080/api/aria2/gid/remove
Content-Type: application/json

{
  "gids": ["2ad3c647483a59d6"],
  "deleteFile": false
}


###
# @nazm details
# @attach-cookie-jar
GET http://localhost:8080/api/aria2/gid/details
Content-Type: application/json

{
  "gid": "80ecaca7ff8057d7"
}

###
# @nazm add_uris
# @attach-cookie-jar
POST http://localhost:5173/api/aria2/add/uris
Content-Type: application/json

{
  "uris": ["http://100.66.197.49:9080/feet/movies/A%20Boy%20Called%20Christmas%20%282021%29.mkv"],
  "options":{}
}

###
# @nazm reg_admin
POST http://localhost:8080/api/auth/reg/admin
Content-Type: application/json

{
  "username": "trasharia",
  "password": "checkcheck"
}

###
# @nazm get_me
# @attach-cookie-jar
GET http://localhost:8080/api/auth/me

###
# @nazm create_user
# @attach-cookie-jar
POST http://localhost:8080/api/auth/create/user
Content-Type: application/json

{
  "username": "heroher",
  "password": "helpcheck",
  "requesterUsername": "adminadmin"
}

###
# @nazm login
# @attach-cookie-jar
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "heroher",
  "password": "helpaddaibi"
}

###
# @nazm delete_user
# @attach-cookie-jar
DELETE http://localhost:8080/api/auth/delete/user
Content-Type: application/json

{

	"targetUsername": "heroher",
  "requesterUsername": "adminadmin"
}


###
# @nazm get_option
# @attach-cookie-jar
POST http://localhost:8080/api/aria2/gid/get/options
Content-Type: application/json
X-CSRF-Token: {{decoded_token}}

{
  "gid": "33895440383f8b8f"
}


###
GET http://clients3.google.com/generate_204


###
# @nazm change_password
# @attach-cookie-jar
POST http://localhost:8080/api/auth/password/change
Content-Type: application/json

{

}

###
# @nazm gen_admin_pass_reset_token
# @attach-cookie-jar
POST http://localhost:8080/api/auth/admin/gen_password_reset_token
Content-Type: application/json

{
	"username": "adminadmin"
}

###
# @nazm reset_admin_password
# @attach-cookie-jar
POST http://localhost:8080/api/auth/admin/reset_password
Content-Type: application/json

{
	"username": "adminadmin",
	"resetToken": "adminadmin:1780820812:c3dvGm3s6rHihX4TeYdxFfbJ0-86grvBpZno6NOuFa4",
	"newPassword": "checkcheck"
}


###
# @nazm change_password
# @attach-cookie-jar
POST http://localhost:8080/api/auth/password/change
Content-Type: application/json

{
	"currentPassword": "checkchck",
	"newPassword": "checkcheck"
}

###
# @nazm logout
# @attach-cookie-jar
POST http://localhost:8080/api/auth/logout
Content-Type: application/json
X-CSRF-Token: {{decoded_csrf_token}}

{

}

### Authentication
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "trasharia",
  "password": "checkcheck"
}


> {%
  -- lua
  -- save the new set authenticated session
  client.global.csrf_token = response.cookies["csrf_token"].value
  client.global.decoded_csrf_token = vim.uri_decode(client.global.csrf_token)

  client.global.auth_token = response.cookies["auth_token"].value
  client.global.decoded_auth_token = vim.uri_decode(client.global.auth_token)
%}

### Dashboard

run #Authentication

GET http://localhost:5173/dashboard
Cookie: csrf_token={{decoded_csrf_token}}


###
# @nazm set_cmd_options
# @attach-cookie-jar
POST http://localhost:8080/api/aria2/cmd/set/options
Content-Type: application/json
X-CSRF-Token: {{decoded_csrf_token}}

{
	"options" : {
		"max-concurrent-downloads": "15"
	}
}


###
# @nazm set_option
# @attach-cookie-jar
POST http://localhost:8080/api/aria2/global/set/options
Content-Type: application/json
X-CSRF-Token: {{decoded_csrf_token}}

{
	"options" : {
		"max-concurrent-downloads": "80"
	}
}


###

GET http://localhost:8080/dashboard













####

# {
#   "amChoking": "true",
#   "bitfield": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80",
#   "downloadSpeed": "119077",
#   "ip": "217.136.2.254",
#   "peerChoking": "false",
#   "peerId": "%2DBT7b0W%2D%7D%B8%14%7F%E7%1B%86%F5%D0F%06%E9",
#   "port": "27959",
#   "seeder": "true",
#   "uploadSpeed": "0"
# }
